### ISSUE TITLE
add depth_exists or similar

### ISSUE THREAD

**Issue by timelyportfolio** [hadley/purrr#242] opened 2016-09-17 14:15 UTC
Often, I want to test if a depth exists, so something like this would be very helpful.  Thanks so much for purrr!

```
depth_exists <- function(l,depth){
  inherits(try(at_depth(l,depth,~NULL),silent=TRUE),"list")
}
```

**Comment by hadley** [comment] 2017-03-03 18:55
I don't really understand what you mean by "if a depth exists"

**Comment by hadley** [comment] 2017-03-03 18:55
Ok, now I see. Closing as duplicate of #243

**Closed by hadley** 2017-03-03 18:55 UTC
