### ISSUE TITLE
transpose() doesn't work as expected when inners keys are disjoint

### ISSUE THREAD

**Issue by louisfc** [hadley/purrr#205] opened 2016-06-22 09:27 UTC
When transposing a list of lists where inner most keys are disjoint, the transpose takes the key from the first inner list and uses that for the key from the second inner list. This also means that in this instance transpose is not it's own inverse.

Given a list like this:

```
test <- list(
  a = list(
    errors = 1
  ),
  b = list(
    violations = 2
  )
)
```

I expect a list like

```
# $errors
# $errors$a
# [1] 1

# $violations
# $violations$b
# [1] 2
```

But get a list like

```
test %>% transpose
# $errors
# $errors$a
# [1] 1

# $errors$b
# [1] 2
```

Transposing the transposed list also does not return the original list:

```
test %>% transpose %>% transpose
# $a
# $a$errors
# [1] 1

# $b
# $b$errors
# [1] 2
```

**Comment by yasminlucero** [comment] 2016-08-23 18:29
This is because transpose matches by position and not by name. Which is fine, but I could really use a method that matches by name as well. There doesn't seem to be any non-awkward way to do this. 

Here is a minimal illustration of a typical use case: 

d1 <- expand.grid(id = c('a', 'b', 'c'), v1 = runif(10), v2 = runif(10)) %>%
  plyr::dlply('id', identity)
d2 <- expand.grid(id = c('c', 'e', 'a', 'f'), v3 = runif(100)) %>%
  plyr::dlply('id', identity)

data.ls <- transpose_byname( list(d1, d2) )

data.ls %>% parallel::clusterApply( bigComplicatedJob )

Narrative: I have two data sources with the same key (id) which I wish to keep separate. I  split each data frame on the common key, and then zip up the two sources so that each element has the subset of d1 and d2 relevant to each key. There is no guarantee that d1 and d2 have the exact same set of key values, and there is definitely no guarantee  that the keys will occur in the same order. Finally, the ultimate motivation for this is that I am probably doing some heavy, embarrassingly parallel operation.

**Comment by hadley** [comment] 2017-03-03 18:45
Duplicate of #164

**Closed by hadley** 2017-03-03 18:45 UTC
