### ISSUE TITLE
yet another form of nothing for type-specific map_*() to handle

### ISSUE THREAD

**Issue by jennybc** [hadley/purrr#181] opened 2016-03-03 18:12 UTC
Continuing our exploration of nothingness (https://github.com/hadley/purrr/issues/110).

It seems type specific map functions should be willing to cope with length zero elements and treat them as null/absent.

``` r
library(purrr)
x <- list(one = list(always = "a", sometimes = "b"),
          two = list(always = "b", sometimes = character()))
x %>% map_chr("always")
#> one two 
#> "a" "b"
x %>% map_chr("sometimes")
#> Error: Result 2 is not a length 1 atomic vector
```

This seems to get the job done for the time being:

``` r
x %>%
  map("sometimes") %>%
  map_if(is_empty, ~ NA_character_) %>% 
  flatten_chr()
#> [1] "b" NA
```

FYI: inspired by an actual list that came from JSON, that came from the Twitter API.

**Comment by hadley** [comment] 2016-03-25 17:53
This is a duplicate of #173

**Closed by hadley** 2016-03-25 17:53 UTC

**Comment by jennybc** [comment] 2016-03-25 20:29
I don't entirely understand why this is a duplicate. @hadley 

``` r
library(purrr)
x <- list("a" = list("b" = character()))
x[[c("a", "b")]]
#> character(0)
x %>% map("b")
#> $a
#> character(0)
x %>% map_chr("b")
#> Error: Result 1 is not a length 1 atomic vector
```

**Comment by hadley** [comment] 2016-03-25 20:53
Because map_chr calls [[. It makes sense to me anyway, so I'll remember

**Comment by almartin82** [comment] 2018-07-16 15:44
Closed issue, but leaving for anyone who is cleaning up JSON and stumbles into this same problem - I resolved this by writing a wrapper around @jennybc's great workaround above:

```
 map_null_chr <- function(.x, .f) {
   map(.x, .f) %>%
     map_if(is_empty, ~ NA_character_) %>%
     flatten_chr()
 }
```
And replaced my offending `map_chr` call.
