### ISSUE TITLE
Interaction `dplyr::mutate` and `purrr::map`

### ISSUE THREAD

**Issue by astamm** [hadley/purrr#105] opened 2015-10-09 10:14 UTC
When trying the bootstrap example from the .md file, I found out that using the formula option to specify the function to be used in `purrr::map` within a call of `dplyr::mutate` does not work. Using the same example, we have indeed:

```r
library(purrr)
library(dplyr)

random_group <- function(n, probs) {
  probs <- probs / sum(probs)
  g <- findInterval(seq(0, 1, length = n), c(0, cumsum(probs)),
                    rightmost.closed = TRUE)
  names(probs)[sample(g)]
}

partition <- function(df, n, probs) {
  replicate(n, split(df, random_group(nrow(df), probs)), FALSE) %>%
    zip_n() %>%
    as_data_frame()
}

msd <- function(x, y) sqrt(mean((x - y) ^ 2))

# Genearte 100 rbootandom test-training splits
boot <- partition(mtcars, 100, c(training = 0.8, test = 0.2))
boot
```

which yields the following dataset:

Source: local data frame [100 x 2]
 
 | test | training
---:  | :---: | :---:
 | (list) | (list)
1 | `<data.frame [7,11]>` | `<data.frame [25,11]>`
2 | `<data.frame [7,11]>` | `<data.frame [25,11]>`
3 | `<data.frame [7,11]>` | `<data.frame [25,11]>`
4 | `<data.frame [7,11]>` | `<data.frame [25,11]>`
5 | `<data.frame [7,11]>` | `<data.frame [25,11]>`
6 | `<data.frame [7,11]>` | `<data.frame [25,11]>`
7 | `<data.frame [7,11]>` | `<data.frame [25,11]>`
8 | `<data.frame [7,11]>` | `<data.frame [25,11]>`
9 | `<data.frame [7,11]>` | `<data.frame [25,11]>`
10 | `<data.frame [7,11]>` | `<data.frame [25,11]>`
.. | ... | ...

Now, if I try to fit a linear regression model `mpg ~ wt` for each training data outside from the `dplyr` framework, i.e., `models <- map(boot$training, ~ lm(mpg ~ wt, data = .))`, then everything works fine, even with the *formula* way of writing the function to be applied to each element of the list.

But, if I do the same code within a `dplyr::mutate` to add the new list-variable `models` directly to the dataset `boot`, i.e., if I do `boot <- boot %>% mutate(models = map(training, ~ lm(mpg ~ wt, data = .)))`, as suggested in the example, I get the following error message:

> Error: invalid term in model formula

It works fine however if I explicitly define the function within `map`, i.e., if instead of `~ lm(mpg ~ wt, data = .)`, I use `function(x) lm(mpg ~ wt, data = x)`.

Is this the expected behavior? Is this a `purrr` issue or a `dplyr` one? I am not sure.

**Comment by lionel-** [comment] 2015-10-09 10:24
Duplicate of #103. This is a dplyr issue.

**Comment by yutannihilation** [comment] 2015-10-11 12:27
@lionel- Thanks. Should I close #103 and report it on dplyr's repo?

**Comment by lionel-** [comment] 2015-10-11 17:20
yes thanks. I think this can't be solved on purrr's side

**Comment by yutannihilation** [comment] 2015-10-11 21:22
Sure. I will. Thanks for your advice!

**Comment by astamm** [comment] 2015-10-13 06:14
Apparently it might also be related to `ggplot2`, since if the package is not loaded, everything goes smoothly.

On Oct 11, 2015, at 11:22 PM, yutannihilation <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure. I will. Thanks for your advice!

**Comment by astamm** [comment] 2015-10-13 06:16
Apparently it might also be related to `ggplot2` since if the package is not loaded, everything goes smoothly.

**Comment by hadley** [comment] 2015-11-11 14:05
Fixed in dplyr.

**Closed by hadley** 2015-11-11 14:05 UTC
