### ISSUE TITLE
by_slice - POSIXct coerced to double

### ISSUE THREAD

**Issue by duf59** [hadley/purrr#184] opened 2016-03-23 10:33 UTC
Passing a data frame containing a time-typed variable to `by_slice` results in a conversion to numeric.

For example:

```{r}
library(purrr)

set.seed(215)
df <- data.frame(id = 1:10,
                 item_type = sample(1L:5L, 10, replace = TRUE),
                 purchase_time = Sys.time(),
                 cost = runif(5, 0, 100))
# id item_type       purchase_time      cost
# 1   1         4 2016-03-23 11:15:31 65.411622
# 2   2         2 2016-03-23 11:15:31 64.465473
# 3   3         1 2016-03-23 11:15:31 80.804265
# 4   4         5 2016-03-23 11:15:31 58.835933
# 5   5         5 2016-03-23 11:15:31  4.204952
# 6   6         4 2016-03-23 11:15:31 65.411622
# 7   7         5 2016-03-23 11:15:31 64.465473
# 8   8         5 2016-03-23 11:15:31 80.804265
# 9   9         2 2016-03-23 11:15:31 58.835933
# 10 10         1 2016-03-23 11:15:31  4.204952
```

If we want compute the minimum `cost` for each `item_type` using `by_slice` as follows:

```{r}
minCost <- function(d) {
  d[which.min(d$cost), ]
}

result <- df %>%
  slice_rows(.cols = "item_type") %>%
  by_slice(minCost, .labels = TRUE, .collate = "rows")
# item_type    id purchase_time      cost
# (int) (int)         (dbl)     (dbl)
# 1         1    10    1458728132  4.204952
# 2         2     9    1458728132 58.835933
# 3         4     1    1458728132 65.411622
# 4         5     5    1458728132  4.204952
```

We see that `purchase_time` was coerced to `dbl`, and we need to re-convert it to `POSIXct` if we need to do further operations with that column.

```{r}
result$purchase_time <- as.POSIXct(result$purchase_time,
                                   origin = "1970-01-01 00:00.00 UTC")
# item_type    id       purchase_time      cost
# (int) (int)              (time)     (dbl)
# 1         1    10 2016-03-23 11:15:31  4.204952
# 2         2     9 2016-03-23 11:15:31 58.835933
# 3         4     1 2016-03-23 11:15:31 65.411622
# 4         5     5 2016-03-23 11:15:31  4.204952
```

Not critical but I was wondering if there is any way to ensure type-stable transformation in such a case?

**Comment by lionel-** [comment] 2016-03-23 12:59
Thanks for the report, this is a duplicate of issue #106

**Closed by lionel-** 2016-03-23 12:59 UTC
