### ISSUE TITLE
Inconsistent behavior with map ~ lapply, and map_n ~ Map

### ISSUE THREAD

**Issue by jonboiser** [hadley/purrr#64] opened 2015-04-16 18:00 UTC
In the package, `map` seems to wrap `lapply`, while `map_n` wraps `Map`, which leads to different behavior. 

For me, the thing that I noticed is that if your input to `map_n` is a character vector, your output is a named list whose names are that character vector. Whereas with plain `map`, it's an unnamed list.

```r
input <- letters[1:5]
map(input, function(x) 1) %>% names #=> NULL
map_n(list(input), function(x) 1) %>% names #=> "a", "b", "c", "d", "e"
```

Before I noticed this, I would have to insert the names using `magrittr::set_names` or `names<-`.

For my own purposes, I actually prefer having the names automatically inserted, so I would just use `map_n` by default from now on.

**Comment by lionel-** [comment] 2015-04-22 21:52
`map()` and `lapply()` have consistent behavior because they always use the names of the input list or vector to name the output. For example, this will work:
```r
letters[1:5] %>% setNames(., .) %>% map(function(x) 1)
```

On the other hand, `Map()` behavior is not so consistent because it only names the output after the input elements if the input is an unnamed character vector. So, if your input vector happens to have names, or to be any other type than a character vector, `Map()` will not recycle the elements into names.

**Comment by hadley** [comment] 2015-05-05 19:44
@lionel- can we suppress that behaviour? (i.e. never automatically name output if input is an unnamed character vector)

**Comment by lionel-** [comment] 2015-05-05 20:06
one use case for `enlist()` that I particularly like is to create functions that take some kind of objects or a list of those objects indistinctly. If your function takes atomic vectors, then it could makes sense to treat data frames as list.
```r
fun <- function(...) {
  dots <- enlist(..., .objects = "data.frame")
  fun_impl(dots)
}
```
then you can use your function in this way: `fun(id = 1:32, mtcars)`.

I figured there could be other use cases so I made the option as general as I could but I admit I have a hard time imagining other situations where this would be useful.

**Comment by lionel-** [comment] 2015-05-05 20:27
oops, the message above was intended for #61.

@hadley I guess this should do it:
```r
map_n <- function (.l, .f, ...) {
    args <- recycle_args(c(.l, list(...)))
    out <- do.call("Map", c(list(quote(.f)), args))

    if (is.character(args[[1]]) && is.null(names(args[[1]]))) {
      names(out) <- NULL
      out
    } else {
      out
    }
}
```

**Comment by hadley** [comment] 2015-05-05 21:06
@lionel- blech. I wonder if we should bite the bullet and implement our own `map` in Rcpp

**Comment by lionel-** [comment] 2015-05-05 21:21
The other way is to use `mapply()` instead of `Map()` (which will be the case anyway when #59 is merged) and set `USE.NAMES` to FALSE and then name the output after the names of the first element of `.x`.

Not that it's much prettier

**Comment by lionel-** [comment] 2015-05-09 11:57
actually to me it's not obvious that `map2()` and `map_n()` should even use the names of the first element. Maybe best to just return an unnamed list in all cases?

**Comment by hadley** [comment] 2015-05-11 12:16
Oh good point - that doesn't make a huge amount of sense.

**Closed** 2015-09-12 18:44 UTC
