### ISSUE TITLE
cases when safely() fail?

### ISSUE THREAD

**Issue by tiernanmartin** [hadley/purrr#258] opened 2016-11-05 18:55 UTC
What causes `safely()` to occasionally fail to return its two values?

While testing a workflow for the `sf` package I stumbled across an instance of `safely()` failing, so I figured I'd post it here.

```
library(tidyverse)
library(sf)

nc <-  st_read(system.file("shape/nc.shp", package="sf"), "nc", crs = 4267)

bind_rows(nc,nc)
## Error in .subset2(x, i, exact = exact) : 
##  attempt to select less than one element in get1index

safe_bind <- safely(bind_rows)

safe_bind(nc,nc)
## $result
## Error in .subset2(x, i, exact = exact) : 
##  attempt to select less than one element in get1index
```

**Comment by tjmahr** [comment] 2016-12-28 17:48
This issue appears that an error is thrown during printing, not during execution of the wrapped function. It _looks like_ a problem with `safely()`, but the `safe_bind()` is successful and there is a `$result` element in the list.

```r
library(tidyverse)
library(sf)

nc <-  st_read(system.file("shape/nc.shp", package="sf"), "nc", crs = 4267)
safe_bind <- safely(bind_rows)

nc_nc <- safe_bind(nc, nc)

# There is a list of two elements.
str(nc_nc, max.level = 2)
#> List of 2
#>  $ result:Classes 'sf' and 'data.frame': 200 obs. of  15 variables:
#>   ..$ AREA     : num [1:200] 0.114 0.061 0.143 0.07 0.153 0.097 0.062 0.091 0.118 0.124 ...
#>   ..$ PERIMETER: num [1:200] 1.44 1.23 1.63 2.97 2.21 ...
#>   ..$ CNTY_    : num [1:200] 1825 1827 1828 1831 1832 ...
#>   ..$ CNTY_ID  : num [1:200] 1825 1827 1828 1831 1832 ...
#>   ..$ NAME     : Factor w/ 100 levels "Alamance","Alexander",..: 5 3 86 27 66 46 15 37 93 85 ...
#>   ..$ FIPS     : Factor w/ 100 levels "37001","37003",..: 5 3 86 27 66 46 15 37 93 85 ...
#>   ..$ FIPSNO   : num [1:200] 37009 37005 37171 37053 37131 ...
#>   ..$ CRESS_ID : int [1:200] 5 3 86 27 66 46 15 37 93 85 ...
#>   ..$ BIR74    : num [1:200] 1091 487 3188 508 1421 ...
#>   ..$ SID74    : num [1:200] 1 0 5 1 9 7 0 0 4 1 ...
#>   ..$ NWBIR74  : num [1:200] 10 10 208 123 1066 ...
#>   ..$ BIR79    : num [1:200] 1364 542 3616 830 1606 ...
#>   ..$ SID79    : num [1:200] 0 3 6 2 3 5 2 2 2 5 ...
#>   ..$ NWBIR79  : num [1:200] 19 12 260 145 1197 ...
#>   ..$ geometry :List of 200
#>   .. .. [list output truncated]
#>  $ error : NULL

# The error happens when trying to print the .$result
nc_nc$result
#> Error in .subset2(x, i, exact = exact): attempt to select less than one element in get1index
```

**Comment by tjmahr** [comment] 2016-12-28 17:48
I recommend closing this issue because it's not a bug with `safely()`.

**Closed** 2017-03-03 19:05 UTC
